Add remote checks and update echo statements

diff --git a/scripts/panfs2ceph b/scripts/panfs2ceph
--- a/scripts/panfs2ceph
+++ b/scripts/panfs2ceph
@@ -124,8 +124,8 @@ while getopts ":hdfver:b:t:" opt; do
         r) remote="$OPTARG" ;;
         b) bucket="$OPTARG" ;;
         t) threads="$OPTARG" ;;
-        :) echo "Error: option ${OPTARG} requires a value" >&2; exit 64 ;;
-        *) echo "Error: option ${OPTARG} is not implemented" >&2; exit 64 ;;
+        :) echo "[panfs2ceph "$(date)"] Error: option ${OPTARG} requires a value" >&2; exit 64 ;;
+        *) echo "[panfs2ceph "$(date)"] Error: option ${OPTARG} is not implemented" >&2; exit 64 ;;
         \?) echo "Invalid option: ${OPTARG}" >&2; exit 64 ;;
     esac
 done
@@ -138,19 +138,25 @@ module load /home/lmnp/knut0297/software/modulesfiles/rclone/1.53.2
 
 if [[ ! $remote ]]
 then
-    echo "The '--remote' option must be specified." >&2
+    echo "[panfs2ceph "$(date)"] The '--remote' option must be specified." >&2
     exit 64
 fi
 if [[ ! $bucket ]]
 then
-    echo "The '--bucket' option must be specified." >&2
-    exit 64
+    echo "[panfs2ceph "$(date)"] The '--bucket' option must be specified." >&2
+    exit 65
 fi
 
 
-# Test if bucket and remote exist
-rclone ls ${remote}: --max-depth 1 || echo "Rclone remote does not exist: $remote"; exit 27
-rclone ls ${remote}:${bucket} --max-depth 1 || echo "Rclone bucket does not exist: $bucket"; exit 28
+# Make sure the remote exists
+if ! rclone listremotes | grep -q "^$remote:\$"
+then
+    echo "[panfs2ceph "$(date)"] Rclone remote does not exist: $remote" >&2
+    exit 28
+fi
+
+
+
 
 
 # ---------------------------------------------------------------------
@@ -178,11 +184,11 @@ done
 # The "positional" input arguments must only be one pathname to a directory, no more or less.
 if [[ ${#positional_arg_readlink[@]} -ne 1 ]]
 then
-    echo "
+    echo "[panfs2ceph "$(date)"]
     check_file_path help:
     One and only one argument is allowed.
     " >&2
-    exit 1
+    exit 2
 fi
 
 root_path_dir=$positional_arg_readlink
@@ -194,12 +200,12 @@ if [[ -d $root_path_dir ]]; then
     # echo "dir: $root_path_dir"
     :
 elif [[ -f $root_path_dir ]]; then
-    echo "file: $root_path_dir" >&2
-    echo "file inputs are not allowed." >&2
+    echo "[panfs2ceph "$(date)"] file: $root_path_dir" >&2
+    echo "[panfs2ceph "$(date)"] file inputs are not allowed." >&2
     exit 1
 else
-    echo "not valid: $root_path_dir" >&2
-    echo "only dirname/path inputs are allowed." >&2
+    echo "[panfs2ceph "$(date)"] not valid: $root_path_dir" >&2
+    echo "[panfs2ceph "$(date)"] only dirname/path inputs are allowed." >&2
     exit 1
 fi
 
@@ -211,16 +217,13 @@ fi
 
 
 # Count the number of ceph objects (files) listed under the input archive dir. If there are any files under this dir name already, stop.
-remote_root_path_dir_filenumber=$(rclone lsf ${remote}:${bucket}$(dirname ${root_path_dir})/$(basename ${root_path_dir}) --max-depth 1 | wc -l)
+remote_root_path_dir_filenumber=$(rclone lsf ${remote}:${bucket}$(dirname ${root_path_dir})/$(basename ${root_path_dir}) --max-depth 1 2> /dev/null | wc -l)
 
 
 if [[ $remote_root_path_dir_filenumber -gt 0 ]]
 then
-    echo "Tier 2 (ceph) already has files saved under this input 'directory name' ($root_path_dir) in this bucket ($bucket). To prevent any possible over-writing of data on ceph, please choose a different panfs directory path to archive or a different ceph bucket."  >&2
+    echo "[panfs2ceph "$(date)"] Tier 2 (ceph) already has files saved under this input 'directory name' ($root_path_dir) in this bucket ($bucket). To prevent any possible over-writing of data on ceph, please choose a different panfs directory path to archive or a different ceph bucket."  >&2
     exit 75
-else 
-    #echo "Ceph does not already has this dir"
-    :
 fi
 
 
@@ -277,6 +280,9 @@ sed -i -e "s|^|$root_path_dir/|" $myprefix.filelist.txt
 # Check for filenames or pathnames that are too long
 # ---------------------------------------------------------------------
 
+# This check is probably pointless because I think the limit is the same for both
+# panfs and ceph -- so if files are on panfs, they should also fit on ceph.
+
 # On object storage (S3, ceph), filenames are irrelevant. Everything is a filename (with dirs being 
 # represented by slash delimiters). Thus, we only need to test for path length.
 # https://stackoverflow.com/questions/6870824/what-is-the-maximum-length-of-a-filename-in-s3
@@ -314,7 +320,7 @@ tee $myprefix.1_copy.slurm << EOF > /dev/null
 #SBATCH --mail-user=$USER@umn.edu
 #SBATCH --partition=amdsmall
 
-echo "["\$(date)"] Script start."
+echo "[panfs2ceph "\$(date)"] Script start."
 
 
 # ---------------------------------------------------------------------
@@ -356,9 +362,9 @@ rclone copy \$dry_run \$verbose_mode / \${remote}:\${bucket} --files-from-raw "\
 if [ ! \$? -eq 0 ]
 then
     # rclone exit status was not zero
-    echo "rclone copy process: FAIL" 2>&1 | tee \$myprefix.COPY_FAILED
+    echo "[panfs2ceph "\$(date)"] Rclone copy process: FAIL" 2>&1 | tee \$myprefix.COPY_FAILED
 else
-    echo "rclone copy process: SUCCESS"
+    echo "[panfs2ceph "\$(date)"] Rclone copy process: SUCCESS"
 fi
 
 
@@ -367,6 +373,17 @@ fi
 # ---------------------------------------------------------------------
 # Verify
 # ---------------------------------------------------------------------
+
+
+# Sleep for a short time to allow rclone to properly list files. If done without
+# a short break, rclone lsf seems fail.
+echo "[panfs2ceph "\$(date)"] Starting verification..."
+echo "[panfs2ceph "\$(date)"] Waiting for 30 sec to allow ceph to index files..."
+sleep 30
+echo "[panfs2ceph "\$(date)"] Getting file list from ceph..."
+
+
+
 
 # Get a file list from ceph (after the transfer)
 rclone lsf -R \$dry_run \$verbose_mode \${remote}:\${bucket}\${root_path_dir} > \$myprefix.filelist_from_ceph.txt
@@ -385,19 +402,21 @@ comm -13 <(sort \$myprefix.filelist.txt) <(sort \$myprefix.filelist_from_ceph.tx
 
 if [[ ! -s \$myprefix.files_on_panfs_but_not_ceph.txt ]]
 then
-   # The file above is empty. There are no files in the *.filelist.txt that are missing from ceph
+   # The file above is empty.
+   echo "[panfs2ceph "\$(date)"] There are no files in the *.filelist.txt that are missing from ceph."
    rm -rf \$myprefix.files_on_panfs_but_not_ceph.txt
 else
-    echo "There are files listed in *.filelist.txt that are not found on ceph. Review: \$myprefix.files_on_panfs_but_not_ceph.txt" >&2
+    echo "[panfs2ceph "\$(date)"] There are files listed in *.filelist.txt that are not found on ceph. Review: \$myprefix.files_on_panfs_but_not_ceph.txt" >&2
 fi
 
 
 if [[ ! -s \$myprefix.files_on_ceph_but_not_panfs.txt ]]
 then
-   # The file above is empty. There are no files on ceph that are not listed in *.filelist.txt
+   # The file above is empty.
+   echo "[panfs2ceph "\$(date)"] There are no files on ceph that are not listed in *.filelist.txt."
    rm -rf \$myprefix.files_on_ceph_but_not_panfs.txt
 else
-    echo "There are files on ceph that are not listed in *.filelist.txt. Review: \$myprefix.files_on_ceph_but_not_panfs.txt" >&2
+    echo "[panfs2ceph "\$(date)"] There are files on ceph that are not listed in *.filelist.txt. Review: \$myprefix.files_on_ceph_but_not_panfs.txt" >&2
 fi
 
 
@@ -410,7 +429,7 @@ fi
 # Job summary info
 # ---------------------------------------------------------------------
 
-echo "["\$(date)"] Script end."
+echo "[panfs2ceph "\$(date)"] Script end."
 
 if [ ! -z \${SLURM_JOB_ID+x} ]; then
     scontrol show job "\${SLURM_JOB_ID}"
@@ -449,7 +468,7 @@ tee $myprefix.2_delete.slurm << EOF > /dev/null
 #SBATCH --mail-user=$USER@umn.edu
 #SBATCH --partition=amdsmall
 
-echo "["\$(date)"] Script start."
+echo "[panfs2ceph "\$(date)"] Script start."
 
 
 # ---------------------------------------------------------------------
@@ -491,9 +510,9 @@ rsync \$dry_run \$verbose_mode -a --force --delete \${empty_dir}/ \${root_path_d
 if [ ! \$? -eq 0 ]
 then
     # rclone exit status was not zero
-    echo "Delete process: FAIL" 2>&1 | tee \$myprefix.DELETE_FAILED
+    echo "[panfs2ceph "\$(date)"] Delete process: FAIL" 2>&1 | tee \$myprefix.DELETE_FAILED
 else
-    echo "Delete process: SUCCESS"
+    echo "[panfs2ceph "\$(date)"] Delete process: SUCCESS"
 fi
 
 # Delete the original archive dir and the temp empty dir
@@ -508,7 +527,7 @@ rm -rf \$empty_dir
 # Job summary info
 # ---------------------------------------------------------------------
 
-echo "["\$(date)"] Script end."
+echo "[panfs2ceph "\$(date)"] Script end."
 
 if [ ! -z \${SLURM_JOB_ID+x} ]; then
     scontrol show job "\${SLURM_JOB_ID}"
@@ -543,7 +562,7 @@ tee $myprefix.3_restore.slurm << EOF > /dev/null
 #SBATCH --mail-user=$USER@umn.edu
 #SBATCH --partition=amdsmall
 
-echo "["\$(date)"] Script start."
+echo "[panfs2ceph "\$(date)"] Script start."
 
 
 # ---------------------------------------------------------------------
@@ -578,7 +597,7 @@ module load /home/lmnp/knut0297/software/modulesfiles/rclone/1.53.2
 
 if [ -d "\$root_path_dir" ]
 then
-    echo "The original dir (\$root_path_dir) still exists on panfs. Stopping restore process. Change the dir name on panfs and re-run restore script." >&2
+    echo "[panfs2ceph "\$(date)"] The original dir (\$root_path_dir) still exists on panfs. Stopping restore process. Change the dir name on panfs and re-run restore script." >&2
     exit 1
 fi
 
@@ -588,6 +607,10 @@ fi
 # rclone
 # ---------------------------------------------------------------------
 
+# Nudge rclone to list the files on bucket (refresh). This seems to help avoid random errors.
+rclone lsf \${remote}:\${bucket} --max-depth 1 2> /dev/null
+
+
 # Copy the files from ceph back to panfs
 rclone copy \$dry_run \$verbose_mode \${remote}:\${bucket}\$root_path_dir \$root_path_dir --transfers \$threads --s3-chunk-size 50M --s3-upload-concurrency 10
 
@@ -595,9 +618,9 @@ rclone copy \$dry_run \$verbose_mode \${remote}:\${bucket}\$root_path_dir \$root
 if [ ! \$? -eq 0 ]
 then
     # rclone exit status was not zero
-    echo "rclone restore process: FAIL" 2>&1 | tee \$myprefix.RESTORE_FAILED
+    echo "[panfs2ceph "\$(date)"] rclone restore process: FAIL" 2>&1 | tee \$myprefix.RESTORE_FAILED
 else
-    echo "rclone restore process: SUCCESS"
+    echo "[panfs2ceph "\$(date)"] rclone restore process: SUCCESS"
 fi
 
 
@@ -606,7 +629,7 @@ fi
 # Job summary info
 # ---------------------------------------------------------------------
 
-echo "["\$(date)"] Script end."
+echo "[panfs2ceph "\$(date)"] Script end."
 
 if [ ! -z \${SLURM_JOB_ID+x} ]; then
     scontrol show job "\${SLURM_JOB_ID}"
