Fix rsync and always print diff files
Previously, if a comparison file was empty, it was deleted. Now, I keep
those empty files to show they are empty. Also, rsync was using the -a
archive flag to delete a dir, which is unnecessary for deleting.

diff --git a/src/subcommands_panfs2ceph b/src/subcommands_panfs2ceph
--- a/src/subcommands_panfs2ceph
+++ b/src/subcommands_panfs2ceph
@@ -390,20 +390,20 @@ comm -13 <(sort \${_myprefix}.filelist.txt) <(sort \${_myprefix}.filelist_from_c
 if [[ ! -s \${_myprefix}.files_on_panfs_but_not_ceph.txt ]]
 then
    # The file above is empty.
-   #echo "[panfs2ceph "\$(date)"] There are no files in the *.filelist.txt that are missing from ceph."
-   rm -rf \${_myprefix}.files_on_panfs_but_not_ceph.txt
+   echo "[panfs2ceph "\$(date)"] There are no files in '\${_myprefix}.filelist.txt' that are missing from ceph."
 else
-    echo "[panfs2ceph "\$(date)"] There are files listed in *.filelist.txt that are not found on ceph. Review: \${_myprefix}.files_on_panfs_but_not_ceph.txt" >&2
+    echo "[panfs2ceph "\$(date)"] There are files listed in '\${_myprefix}.filelist.txt' that are not found on ceph."
+    echo "[panfs2ceph "\$(date)"] Review: '\${_myprefix}.files_on_panfs_but_not_ceph.txt'" >&2
 fi
 
 
 if [[ ! -s \${_myprefix}.files_on_ceph_but_not_panfs.txt ]]
 then
    # The file above is empty.
-   #echo "[panfs2ceph "\$(date)"] There are no files on ceph that are not listed in *.filelist.txt."
-   rm -rf \${_myprefix}.files_on_ceph_but_not_panfs.txt
+   echo "[panfs2ceph "\$(date)"] There are no files on ceph that are not listed in '\${_myprefix}.filelist.txt'."
 else
-    echo "[panfs2ceph "\$(date)"] There are files on ceph that are not listed in *.filelist.txt. Review: \${_myprefix}.files_on_ceph_but_not_panfs.txt" >&2
+    echo "[panfs2ceph "\$(date)"] There are files on ceph that are not listed in '\${_myprefix}.filelist.txt'." 
+    echo "[panfs2ceph "\$(date)"] Review: '\${_myprefix}.files_on_ceph_but_not_panfs.txt'" >&2
 fi
 
 
@@ -486,7 +486,7 @@ _empty_dir=\${_myprefix_dir}/empty_dir
 
 mkdir -p \${_empty_dir}
 
-rsync \${_dry_run} -v -a --force --delete \${_empty_dir}/ \${_root_path_dir}/
+rsync \${_dry_run} -v -r --force --delete \${_empty_dir}/ \${_root_path_dir}/
 
 
 
@@ -638,8 +638,6 @@ HEREDOC
 
 
     tee ${_myprefix}.readme.md << HEREDOC > /dev/null
-
-
 # panfs2ceph archive
 
 Archive initated (Y-m-d-HMS):  
@@ -647,21 +645,22 @@ ${_archive_date_time}
 
 ## Introduction
 
-This directory (\`${_root_path_dir}\`) was archived from MSI's \`panfs\` (tier 1) storage to its \`ceph\` tier 2 storge. All data inside the directory was copied using \`rclone\` which uses MD5 checksums on every transfer to ensure data integrity. After the data was copied, it was deleted from \`panfs\`. 
+This directory (\`${_root_path_dir}\`) was archived from MSI's *panfs* (tier 1) storage to its *ceph* tier 2 storge. All data inside the directory was copied using \`rclone\` which uses MD5 checksums on every transfer to ensure data integrity. After the data was copied, it was deleted from \`panfs\`. 
 
 
 ## How this works
 
-* A program called \`panfs2ceph\` found all the files in a directory to archive and created a file list text file.
+* A program called \`cephtools panfs2ceph\` found all the files in the directory above and created a file list text file.
 * Then the program created a slurm job file (bash script) that can be run to copy all files from panfs to ceph.
 * The program also created a slurm job file (bash script) to delete the original data from panfs.
 * The program also created this README file.
 * The program does not actually run these slrum job scripts. You must do that manually after reviewing the file list, etc.
+* After running the slurm job scripts, you should review the stderr and stdout log files and the new file lists that get created during the \`*.1_copy.slurm\` job.
 
 
 ## Notes:
 
-* A new dir is created next to the original that contains these archive-related files and scripts.
+* A new dir is created next to the original that contains these archive-related files and scripts. This dir should have the same permissions as the original dir (that got archived). 
 * File modification times/dates should be preserved between transfers. However, if files are transferred from ceph back to panfs, the original modification times of directories will be lost (i.e. block storage like tier 2 does not have directories, so their mod times can't be preserved).
 
 
@@ -673,7 +672,7 @@ Variable Name | Value
 -----------|----------
 Archive date and time | ${_archive_date_time}
 Directory to archive | ${_root_path_dir}
-Directory name for archive files | ${_myprefix}
+Archive transfer prefix | ${_myprefix}
 Directory path for archive files | ${_myprefix_dir}
 Ceph UserID | $(s3info info | grep username | awk -F': ' '{print $2}')
 Ceph Remote Name | ${_remote}
@@ -688,7 +687,7 @@ User doing transfer | $USER
 You can use a variety of tools to browse data stored on ceph. For example:
 
 1. rclone (e.g. \`rclone ls ${_remote}:${_bucket}${_root_path_dir}\`). This requires a properly configured \`~/.config/rclone/rclone.conf\` file. 
-2. s3cmd (e.g. \`s3cmd ls -r s3://${_bucket}${_root_path_dir}\`). This requires a properly configured \`~/.s3cfg\` file. 
+2. s3cmd (e.g. \`s3cmd ls -r s3://${_bucket}${_root_path_dir}\`). This requires a properly configured \`~/.s3cfg\` file. Note: different MSI users might use different rclone remote names -- use *your* remote name. 
 3. GUI based file browser (e.g. FileZilla, Panic's Transmit, CyberDuck, etc.)
 
 
@@ -701,9 +700,7 @@ The original data was deleted, but might still be stored on \`panfs\` as a snaps
 
 ### Restore from ceph back to panfs
 
-Depending on user permissions, the data can be copied from ceph back to panfs using \`rclone\` or other methods. For example, running ${_myprefix}.3_restore.slurm job script should copy the data from ceph back to panfs in its original location.
-
-
+Depending on user permissions, the data can be copied from ceph back to panfs using \`rclone\` or other methods. For example, running \`${_myprefix}.3_restore.slurm\` job script should copy the data from ceph back to panfs in its original location.
 
 
 
